# Generated by Django 3.1.7 on 2023-04-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230501_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='is_done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
