# Generated by Django 4.2.1 on 2023-05-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(null=True),
        ),
    ]
