# Generated by Django 4.0.3 on 2023-05-13 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='project_user',
        ),
        migrations.AddField(
            model_name='projecttask',
            name='user_task',
            field=models.ManyToManyField(related_name='user_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
