# Generated by Django 4.0.3 on 2023-05-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_projecttask_project_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttaskcomment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
